name: Deploy to SVN

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SVN
      run: sudo apt-get install subversion

    - name: Deploy to SVN
      run: |
        svn checkout --non-interactive --no-auth-cache --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} ${{ secrets.SVN_REPO_URL }}   woocommerce-loyalty-rewards
        cp -r assets/* woocommerce-loyalty-rewards/trunk/assets/
        cp -r src/* woocommerce-loyalty-rewards/trunk/
        mkdir -p woocommerce-loyalty-rewards/tags/${{ github.event.release.tag_name }}  
        cp -r src/* woocommerce-loyalty-rewards/tags/${{ github.event.release.tag_name }}
        cd woocommerce-loyalty-rewards
        svn add . --force
        svn commit -m "Automatic deployment from GitHub Action"   --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }}
        svn update