name: Deploy to WordPress.org
on:
  push:
    tags:
    - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          bash build.sh

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.WORDPRESS_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WORDPRESS_SVN_USERNAME }}
          SOURCE_DIR: dist/
          SLUG: beans-woocommerce-loyalty-rewards
