name: Deploy to SVN

on:
  push:
    branches:
      - feature/DEV-818  # Adjust this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SVN
      run: sudo apt-get install subversion

    - name: Deploy to SVN
      run: |
        svn checkout ${{ secrets.SVN_REPO_URL }}   woocommerce-loyalty-rewards 
        cp -r * woocommerce-loyalty-rewards/
        cd woocommerce-loyalty-rewards
        svn add . --force
        svn commit -m "Automatic deployment from GitHub Action"
        svn update ${{ secrets.SVN_REPO_URL }}
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}